/*
Copyright 2020 The KubeSphere Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
	optenantv1alpha1 "kubesphere.io/api/optenant/v1alpha1"
	scheme "kubesphere.io/kubesphere/pkg/client/clientset/versioned/scheme"
)

// OptenantsGetter has a method to return a OpTenantInterface.
// A group's client should implement this interface.
type OptenantsGetter interface {
	OpTenants() OpTenantInterface
}

// OpTenantInterface has methods to work with OpTenant resources.
type OpTenantInterface interface {
	Create(ctx context.Context, optenant *optenantv1alpha1.OpTenant, opts v1.CreateOptions) (*optenantv1alpha1.OpTenant, error)
	Update(ctx context.Context, optenant *optenantv1alpha1.OpTenant, opts v1.UpdateOptions) (*optenantv1alpha1.OpTenant, error)
	UpdateStatus(ctx context.Context, optenant *optenantv1alpha1.OpTenant, opts v1.UpdateOptions) (*optenantv1alpha1.OpTenant, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*optenantv1alpha1.OpTenant, error)
	List(ctx context.Context, opts v1.ListOptions) (*optenantv1alpha1.OpTenantList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *optenantv1alpha1.OpTenant, err error)
	OpTenantExpansion
}

// optenant implements OpTenantInterface
type optenant struct {
	client rest.Interface
}

// newOptenants returns a OpTenant
func newOptenants(c *OpTenantV1alpha1Client) *optenant {
	return &optenant{
		client: c.RESTClient(),
	}
}

// Get takes name of the optenant, and returns the corresponding optenant object, and an error if there is any.
func (c *optenant) Get(ctx context.Context, name string, options v1.GetOptions) (result *optenantv1alpha1.OpTenant, err error) {
	result = &optenantv1alpha1.OpTenant{}
	err = c.client.Get().
		Resource("optenants").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of OpTenants that match those selectors.
func (c *optenant) List(ctx context.Context, opts v1.ListOptions) (result *optenantv1alpha1.OpTenantList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &optenantv1alpha1.OpTenantList{}
	err = c.client.Get().
		Resource("optenants").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested optenants.
func (c *optenant) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("optenants").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a optenant and creates it.  Returns the server's representation of the optenant, and an error, if there is any.
func (c *optenant) Create(ctx context.Context, workspace *optenantv1alpha1.OpTenant, opts v1.CreateOptions) (result *optenantv1alpha1.OpTenant, err error) {
	result = &optenantv1alpha1.OpTenant{}
	err = c.client.Post().
		Resource("optenants").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(workspace).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a optenant and updates it. Returns the server's representation of the optenant, and an error, if there is any.
func (c *optenant) Update(ctx context.Context, optenant *optenantv1alpha1.OpTenant, opts v1.UpdateOptions) (result *optenantv1alpha1.OpTenant, err error) {
	result = &optenantv1alpha1.OpTenant{}
	err = c.client.Put().
		Resource("optenants").
		Name(optenant.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(optenant).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *optenant) UpdateStatus(ctx context.Context, optenant *optenantv1alpha1.OpTenant, opts v1.UpdateOptions) (result *optenantv1alpha1.OpTenant, err error) {
	result = &optenantv1alpha1.OpTenant{}
	err = c.client.Put().
		Resource("optenants").
		Name(optenant.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(optenant).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the optenant and deletes it. Returns an error if one occurs.
func (c *optenant) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("optenants").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *optenant) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("optenants").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched optenant.
func (c *optenant) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *optenantv1alpha1.OpTenant, err error) {
	result = &optenantv1alpha1.OpTenant{}
	err = c.client.Patch(pt).
		Resource("optenants").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
