/*
Copyright 2020 The KubeSphere Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
	v1alpha1 "kubesphere.io/api/optenant/v1alpha1"
)

// OpTenantLister helps list Workspaces.
// All objects returned here must be treated as read-only.
type OpTenantLister interface {
	// List lists all OpTenants in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.OpTenant, err error)
	// Get retrieves the OpTenant from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.OpTenant, error)
	OpTenantListerListerExpansion
}

// optenantLister implements the OpTenantLister interface.
type optenantLister struct {
	indexer cache.Indexer
}

// NewOpTenantListerLister returns a new OpTenantLister.
func NewOpTenantListerLister(indexer cache.Indexer) OpTenantLister {
	return &optenantLister{indexer: indexer}
}

// List lists all OpTenant in the indexer.
func (s *optenantLister) List(selector labels.Selector) (ret []*v1alpha1.OpTenant, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.OpTenant))
	})
	return ret, err
}

// Get retrieves the OpTenant from the index for a given name.
func (s *optenantLister) Get(name string) (*v1alpha1.OpTenant, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("optenant"), name)
	}
	return obj.(*v1alpha1.OpTenant), nil
}
